# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install Norminette
        run: |
             python3 -m pip install --upgrade pip setuptools
             python3 -m pip install norminette
      - name: Run Norminette
        run: norminette *.c *.h
      - name: Install llvm clang
        run: |
             brew install llvm
             echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH
      - name: make address
        run: |
              make address
              ./unit_test
        working-directory: ./unit_tests
      - name: make leak
        run: |
              make leak
              ./unit_test
        working-directory: ./unit_tests
      - name: Checkout libft-unit-test
        uses: actions/checkout@v2
        with:
          repository: alelievr/libft-unit-test
          path: libft-unit-test
      - name: run libft-unit-test
        run: |
             sed -i "" "/^LIBFTDIR/s/libft/..\/libft/" Makefile
             sed -i "" "/^CC/s/clang/gcc/" Makefile
             make re
             ./run_test
             ! cat result.log | grep -e "KO" -e "FAILED" -e "CRASH" -e "TIMEOUT" -e "MISSING"
        working-directory: ./libft-unit-test
